package readcard;

import java.io.BufferedWriter;
import java.io.FileWriter;
import org.jasypt.encryption.pbe.StandardPBEStringEncryptor;

/**
 * @author Iain Woodburn
 */
public class Dialogue extends javax.swing.JDialog {

    ReadCard rc = new ReadCard();
    
    /**
     * Creates new form Dialogue
     */
    public Dialogue() {
        initComponents();
    }

    private String encrypt(String rawString){
        
        String seed = "password";
        
        StandardPBEStringEncryptor encryptor = new StandardPBEStringEncryptor();
        encryptor.setPassword(seed);
        return encryptor.encrypt(rawString);
    }
    
    private boolean writeToFile(String text, String filepath, String filename){
        
        try { 
          //Creates new file, even if one already exists, good for security
          FileWriter fWriter = new FileWriter(filepath.concat(filename)); 
          BufferedWriter writer = new BufferedWriter(fWriter);
          writer.write(text);
          writer.newLine();
          writer.close();
          //Signals main method that user is done and the information from the card is now in the file
          ReadCard.done = true; 
          System.err.println("Your input of " + text.length() + " characters was saved.");
          this.dispose();
        } catch (Exception e) {
            System.out.println("Error!");
        }
        
        return false;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        headerBox = new javax.swing.JLabel();
        password_box = new javax.swing.JPasswordField();
        readCardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        headerBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        headerBox.setForeground(new java.awt.Color(51, 51, 255));
        headerBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerBox.setText("Swipe card and click Read Card");

        readCardButton.setText("Read Card");
        readCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readCardButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(headerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(readCardButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(password_box, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(password_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readCardButton)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>                        

    private void readCardButton(java.awt.event.ActionEvent evt) {                                
        char[] password = password_box.getPassword();
        String filePath = "C:\\Users\\Marcus Woodburn\\Documents\\";
        String fileName = "employeeCardInfo.txt";
        String strPass = new String(password); //Converts from char array to string
        //Encrypts string directly after it is collected and BEFORE it is passed or written to the file
        strPass = encrypt(strPass); 
        writeToFile(strPass , filePath , fileName);
        System.out.println("Your password is: " + strPass);
    }                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dialogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel headerBox;
    private javax.swing.JPasswordField password_box;
    private javax.swing.JButton readCardButton;
    // End of variables declaration                   
}
